feat: разработать согласно ТЗ Диплом
aigeley/java-explore-with-me pull request #2
Opened 2023-01-14 01:27 UTC by aigeley

2023-01-14 10:32 UTC, EugeneLenkevich requested changes
Привет, Андрей, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошел до дипломной работы, ты крут без вариантов :)

Далее, 
наша цель в том, чтобы сделать красоту в этом проекте, все таки диплом, вдруг по нему будут оценивать навыки. Я оставил кучку коментариев, будут вопросы, задавай, не стесняйся, немножко допилить осталось :)

Смотрю ты использовал многие технологии, не освещенные в курсе, это очень круто :) 

Так же
1. Не увлекайся с наследованием. Оно должно быть логически и семантически обоснованным и точно не усложнять код, иначе раби чего это все, оверинжингиринг. Ну и вообще, клмпозиция в большинстве случае проще и гибче чем наследование :)
2. Будь поаккурантей, пожалуйста, с именами методов, это очень сильно влияет на читаемость кода :)
 
Удачи!

2023-01-14 10:32 UTC, EugeneLenkevich commented on element-library/src/main/java/ru/practicum/element/api/ElementApiController.java
> +    protected final HttpServletRequest request;
А зачем нужна ссылка на запрос, он же каждый раз разный, если он тебе так уж нужен, то добавь его как дополнительный параметр в метод контроллера, но хранить его в поле пожалуй бессмысленно :)

2023-01-14 10:32 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/api/AdminEventsApiController.java
> +    protected AdminEventsApiController(AdminEventsService service, HttpServletRequest request) {
HttpServletRequest 

Каждое обращение к контроллеру - это отдельный объект этого типа, незачем его хранить :)

2023-01-14 10:32 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/api/CategoriesApiController.java
> +public class CategoriesApiController extends ElementApiController<CategoriesService> implements CategoriesApi {
А нужно ли тут наследование от ElementApiController, какой то особой семантики этот базовый класс не добавляет, ну кроме ссылки на сервис, как мне кажется только немного усложняет... проще заинжектить бин напрямую в контроллер чем городить иерархию, это же дополнительная конитивная нагрузка на того кто будет с этим кодом разбираться :)

2023-01-14 10:32 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/api/EventsApiController.java
> +@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
Не совсем понял, код чтоль сгенерированный по свагеру? Ладно, ок, пусть будет так :)

2023-01-14 10:32 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/Category.java
> +    private Long id;
Ну так и запихал бы id  в базовый класс :)

https://sysout.ru/nasledovanie-s-mappedsuperclass/

2023-01-14 10:32 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/Category.java
> +        return Objects.equals(this.id, category.id) &&
Вообще, сущность - это не просто объект, это представление строки таблицы базы данных, а строку таблицы однозначно определяет ее идентификатор, и потому, соотвественно, для сущностей equals и hashCode стоит определять на основе id (первичного ключа). 

Остальные поля, при этом, могут вообще быть разными, то есть могут существовать разные версии одного и того же объекта, но как это разруливатеся - это уже отдельная история.
 
https://habr.com/ru/post/268903/

2023-01-14 10:32 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/service/AdminCategoriesService.java
> +    CategoryDto updateCategory(CategoryDto categoryDto);
AdminCategoriesService 

Category уже есть в имени сервиса, в методах можно уже и не указывать ,и так понятно
add(..)
update(..)
...

2023-01-14 10:32 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/service/AdminCategoriesServiceImpl.java
> +    public CategoryDto updateCategory(CategoryDto categoryDto) {
А давай ка еще над все методы, которые изменяют данные (insert, update и delete) будем оформлять как логические транзакции, так будет правильнее. То есть добавим аннотацию @Transactional над ними

2023-01-14 10:32 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/service/AdminEventsServiceImpl.java
> +    public List<EventFullDto> getEvents_2(List<Long> users, List<StateEnum> states, List<Long> categories,
getEvents_2 - так лучше не называть методы, с какими то цифрами непонятными, что это означает :)

2023-01-14 10:32 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/service/UsersEventsServiceImpl.java
> +    public EventFullDto updateEvent_1(Long userId, UpdateEventRequest updateEventRequest) {
updateEvent_1 !!!!

2023-01-15 21:02 UTC, aigeley commented on element-library/src/main/java/ru/practicum/element/api/ElementApiController.java
> +    protected final HttpServletRequest request;
Исправлено

2023-01-15 21:02 UTC, aigeley commented on ewm-service/src/main/java/ru/practicum/ewm/api/AdminEventsApiController.java
> +    protected AdminEventsApiController(AdminEventsService service, HttpServletRequest request) {
Исправлено

2023-01-15 21:02 UTC, aigeley commented on ewm-service/src/main/java/ru/practicum/ewm/api/CategoriesApiController.java
> +public class CategoriesApiController extends ElementApiController<CategoriesService> implements CategoriesApi {
Исправлено

2023-01-15 21:03 UTC, aigeley commented on ewm-service/src/main/java/ru/practicum/ewm/api/EventsApiController.java
> +@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
Исправлено, убрал аннотации `@Generated` над интерфейсами контроллеров - изначально классы создавались с помощью генератора, но позже вносились ручные правки.

2023-01-15 21:05 UTC, aigeley commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/Category.java
> +    private Long id;
Заменил наследование от базового класса на реализацию интерфейса. Не до конца понял, если выносить поле id в базовый класс, можно ли на него навесить аннотации с названиями поля и сиквенса для каждой отдельной таблицы (у меня везде отличаются)?

2023-01-15 21:06 UTC, aigeley commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/Category.java
> +        return Objects.equals(this.id, category.id) &&
Исправил для всех `@Entity`-классов и проекций для БД. При реализации equals и hashCode использовал рекомендации из статьи, подойдёт в таком виде?
 https://thorben-janssen.com/ultimate-guide-to-implementing-equals-and-hashcode-with-hibernate/#Using_a_Generated_Primary_Key 
 Документацию про блокировки прочитал, но пока не совсем понял, в каких случаях их использовать. Для текущего приложения будет достаточно изоляции на уровне транзакций с уровнем Isolation.DEFAULT, который присваивается при проставлении аннотации `@Transactional`?

2023-01-15 21:06 UTC, aigeley commented on ewm-service/src/main/java/ru/practicum/ewm/service/AdminCategoriesService.java
> +    CategoryDto updateCategory(CategoryDto categoryDto);
Исправлено. Оригинальные названия оставил в параметре operationId аннотации `@Operation`, для соответствия исходной спецификации OpenAPI.

2023-01-15 21:07 UTC, aigeley commented on ewm-service/src/main/java/ru/practicum/ewm/service/AdminCategoriesServiceImpl.java
> +    public CategoryDto updateCategory(CategoryDto categoryDto) {
Исправлено, проставил аннотации `@Transactional` над методами изменяющими данные (или на уровне класса, если все методы изменяют данные). Можешь посоветовать, что ещё можно почитать про `@Transactional`? Из теории курса, честно говоря, совсем не отложилось, как её правильно применять...

2023-01-15 21:07 UTC, aigeley commented on ewm-service/src/main/java/ru/practicum/ewm/service/AdminEventsServiceImpl.java
> +    public List<EventFullDto> getEvents_2(List<Long> users, List<StateEnum> states, List<Long> categories,
Исправлено

2023-01-15 21:07 UTC, aigeley commented on ewm-service/src/main/java/ru/practicum/ewm/service/UsersEventsServiceImpl.java
> +    public EventFullDto updateEvent_1(Long userId, UpdateEventRequest updateEventRequest) {
Исправлено

2023-01-16 04:54 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/Category.java
> +    private Long id;
Ну если отличаются то не надо делать его общим на всех, тут же наоборот фишка в том чтобы все было сделано единообразно. Ок, пусть так и остается :)

2023-01-16 04:57 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/model/category/Category.java
> +        return Objects.equals(this.id, category.id) &&
В статье как раз про первичный ключ речь и идет. 

Про блоокировки просто для общего развития, как пример того чо жизненный цикл сущностей бывает достаточно нетривиален и то что сущности, представляющий один и тот же объектв БД, могу быть не эквивалентный (равные версии) :)

2023-01-16 05:04 UTC, EugeneLenkevich approved these changes
Спасибо за исправление :)

Ох, сколько переименований, ПР даже до конца не загружается, пришлось вторую половину отдельно прощелкивать, но теперь все ок :)

2023-01-16 09:41 UTC, aigeley commented on ewm-service/src/main/java/ru/practicum/ewm/service/AdminCategoriesServiceImpl.java
> +    public CategoryDto updateCategory(CategoryDto categoryDto) {
Спасибо, почитаю!

2023-01-16 09:41 UTC, merged